version: '3.8'
services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: keba_logger
      POSTGRES_USER: logger
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
